# Generated by Django 5.0.6 on 2024-06-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_password_hash_user_password_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
