# Generated by Django 5.0.6 on 2024-06-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_hash',
        ),
    ]
