# Generated by Django 5.0.6 on 2024-08-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='ors_coordinates',
            new_name='osrm_coordinates',
        ),
    ]
