name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Create .env file
        run: |
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" > .env
          echo "DB_HOST=go_db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "DB_NAME=email_verification" >> .env
          echo "RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/" >> .env

      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Run Go tests
        run: |
          docker-compose -f docker-compose.yml run --rm go_test go test ./...

      - name: Run Django tests (if any)
        run: |
          docker-compose -f docker-compose.yml run --rm django python manage.py test

      - name: Stop and remove containers
        run: |
          docker-compose -f docker-compose.yml down
